sudo: false
language: php
php:  
  - 5.5
  - 5.6
  - hhvm
  - 7
before_script:
  - composer self-update
  - wget https://phar.phpunit.de/phpunit.phar
  - composer install
script:
  - php phpunit.phar --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
